name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Deploy to On-Premise Host
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        PATH: $PATH:/usr/local/bin:/usr/bin:/bin
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        scp -i ~/.ssh/deploy_key -r build/ $DEPLOY_USER@$DEPLOY_HOST:reactiv/build/
        ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST "export PATH=$PATH; cd ~/reactiv; if lsof -t -i:3000 > /dev/null; then kill $(lsof -t -i:3000); fi"

